-- 코드를 입력하세요
# 총주문량이 3,000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림의 맛을 
# 총주문량이 큰 순서대로 조회
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF, ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR AND TOTAL_ORDER>=3000 AND ICECREAM_INFO.INGREDIENT_TYPE="fruit_based"